FDOS/kernel

kernel/task.c
Some ancient "New Executable" (`NE`) programs set `exMinAlloc` in the `MZ` header to `0xffff`, to signify that they should not be run as normal `MZ` programs at all:
```
00000000  4d 5a 40 00 01 00 00 00  04 00 ff ff ff ff 00 00
00000010  00 00 00 00 00 00 00 00  40 00 00 00 00 00 00 00
00000020  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00
00000030  00 00 00 00 00 00 00 00  00 00 00 00 40 00 00 00
00000040  4e 45 04 00 9b 00 07 00  00 00 00 00 06 40 02 00
...
```
The kernel should reject these programs, rather than try to run them (and crash the system).
=> EXEC (func 0x4b): fix: do not crash if exMinAlloc == 0xffff

kernel/inthndlr.c, kernel/task.c
- Upon creation, initialize the PSP version field to os_setver_minor / os_setver_major.
- When calling Function 30h, return the contents of the current PSP's version field to the caller.
=>  Function 30h (Get DOS Version): Get DOS version from PSP

.gitattributes, .travis.yml, travis_build.sh, travis_test.sh
Automatic building of FreeDOS with the GCC compiler using [Travis](https://travis-ci.com/) upon every push or PR. If you have a test suite, then automatic testing can be added too.
=> Travis: Initial build attempt

kernel/dosfns.c, kernel/inthndlr.c, kernel/proto.h
~~~
DOS provides the interrupt 2f/12xx functions for use by
filesystem redirectors in order that they do not need to access
structures and variables using undocumented methods. Interrupt
2f/1217 is a function used by a redirector to get the CDS entry
corresponding to a drive without iterating the CDS array found
via SYSVARS LOL.
FreeDOS currently validates the flags in CDS entry before
deciding whether to return the entry to the caller. This behaviour
prevents a redirector receiving the CDS entry corresponding to
an as yet unassigned drive so preventing any new drive mapping.
I've tested the following flavours of DOS and only FreeDOS does this.
DR-DOS
6.00-930319 7.00 7.01 7.02-971119 7.02-980123 7.03 8.00
MS-DOS
3.10 3.20 3.21 3.30-Nec 3.30 3.31 4.01 5.00 6.00 6.20 6.21 6.22
7.00 7.10 …
=> int2f: Allow 1217h function to return new CDS entry

makefile
Currently the sed trickery for gcc is only setup on the all target, but
if we want to do `make COMPILER=gcc clean all` the clean will fail.
Setup and remove the GNUmakefiles for each main target.
=> Make: Allow clean and clobber to work with gcc

hdr/pcb.h, kernel/entry.asm, kernel/int2f.asm, kernel/inthndlr.c, kernel/kernel.asm, kernel/nls.c, kernel/proto.h
This changes the interface between `reloc_call_int2f_handler` (`int2f.asm`) and `int2F_12_handler( )` (`inthndlr.c`) so that
* `int2F_12_handler( )` will not try to output values to its caller by passing "back" input parameter values
* `reloc_call_int2f_handler` will switch to an internal stack before calling `int2F_12_handler( )`, so that `SS` == `DGROUP` as expected by the latter.
This partly addresses https://github.com/FDOS/kernel/issues/11 .
(The call to `syscall_MUX14( )` in `int2f.asm` seems to have similar issues, and should probably also be updated.)
=> Fix call interfaces around int2F_12_handler( ), syscall_MUX14( ), and (mostly) int21_syscall( )

kernel/config.c, kernel/main.c
* Add initialization of the PSP in processing the CONFIG.SYS
=> Fix Func 30h (Get DOS Version) return version 0.0 in config.sys

travis_build.sh, travis_test.sh
Watcom compiler is downloaded and extracted if necessary. On Travis this
will be always, but if you build locally multiple times using
./travis_build, it will use the previous watcom installation.
=> Travis: Build and test with both GCC and Watcom

hdr/portab.h
correct I186 and I386 macros definition to work with all Open Watcom toolchain versions
command line definition macro has "1" value but in header file it is defined as blank value
anyway I86/I186/I386 macros usage is not transparent, it is definition duplicity in header file and on command line
it is wrong solution even if it works on most of compilers (command line macro re-definition is hidden)
=> correct I186 and I386 macros definition

boot/boot.asm, boot/oemboot.asm
Reference: https://www.bttr-software.de/forum/forum_entry.php?id=16934
The SBC188 video ROM-BIOS handling returns with al=0Ah (LF)
upon interrupt 10h function 0Eh calls that scroll the screen.
This made the FAT12 boot loader crash when booting FreeDOS
off a 1440 KiB diskette. While a fix is expected from their
side too, hardening the loader too is the right thing to do.
With the way this fix is implemented by this commit, it only
needs one additional byte for the loader. The error message
changes from "Error!." to just "Error!", other than
that the behaviour is the same.
The FAT32 loaders already used zero-terminated strings and
thus were not affected by the dependence.
=> boot: fix Int10.0E expected not to alter al (SBC188)

boot/boot.asm, boot/boot32.asm, boot/boot32lb.asm, boot/oemboot.asm
Reference: https://hg.ulukai.org/ecm/instsect/file/33218c729b43/instsect.asm#l1257
lDOS's instsect recently started to default to checking
the filesystem ID string in order to validate that the
boot sector loader to write matches the detected FS.
Using the /S=filename option or building instsect to
include the FreeDOS kernel's loaders would require use
of the /SN switch without this commit.
In addition, boot.asm and oemboot.asm are made to check
that exactly one of the ISFAT12 and ISFAT16 defs is
defined so as to select the FS. Prior to this commit
using both or neither def would silently result in a
broken loader.
=> boot: allow instsect to match the filesystem ID string

kernel/fatfs.c
After comparison with DR-DOS 7.01 and MS-DOS 6.22 over at Dosemu2 it
was seen that rmdir of a directory having the _A_RDONLY bit set should
succeed. This patch makes that change.
For reference the test report can be found in the fdpp issue
https://github.com/dosemu2/fdpp/issues/161. An identical patch has been applied there.
=> FATFS: rmdir of read only directories is valid

.github/workflows/ci-build.yml, README.md
Adds the build status badge, support for the '[skip ci]' keyword in the commit message and only upload build artefacts from the master repo/branch.
=> CI: Update workflow and readme badge

docs/build.txt, kernel/inthndlr.c
Changes:
* I recently [added to my `gcc-ia16` toolchain](https://github.com/tkchia/build-ia16/releases/tag/20200321) some support for compiling functions to run with the stack outside of the data segment (`%ss` ≠ `.data`).  In the first commit, I modify `int21_syscall( )` --- which implements `int $0x21` functions that do not switch to DOS's internal stacks --- so that it uses this compiler feature if available.
* The second commit updates `docs/build.txt` on the Ubuntu distributions for which pre-compiled `gcc-ia16` toolchains are available.
Thank you!
=> ia16-elf-gcc: use new SS != DGROUP support for int21_syscall( )

kernel/task.c
Patch ported from
* https://github.com/dosemu2/fdpp/commit/f49252ac6b89a7bee0dd5ac90b9509918c19dd33
See
* https://github.com/dosemu2/fdpp/issues/112
* https://github.com/FDOS/kernel/issues/38
=> task: don't zero parent_psp on 0x26

kernel/fcbfns.c
The "next" part of this function never returned any results, initialise
only on the first call.
Fix by @stsp, minor edits @andrewbird
=> fcbfns: Fix for FcbFindFirstNext [fixes #40]

.github/workflows/ci-build.yml
An oversight, I forgot to include the new share output in the uploaded snapshot file!
=> Build: Update upload artefact file selection

kernel/config.c
Refer to https://github.com/FDOS/kernel/issues/73
=> ecm 2022-05 gcc crash fix

kernel/init-mod.h, kernel/inithma.c, kernel/kernel.asm
Some assembly tricks:
* SMC instead of checking the XMS driver address
in the DOS DS stub,
* SMC so that the address goes right into a
`call far immediate` instruction,
* use `repe cmpsw` to compare multiple words (saves
space over the individual word compares),
* near calls to far functions use push cs to build
a far-call stack frame,
* segments 0 and FFFFh generated by segment arithmetic
instead of loading from memory,
* common case (A20 already enabled) made to be the case
where the conditional branch just falls through, which
may be slightly better.
=> ecm 2022-05 optimise entry

kernel/kernel.asm, kernel/makefile, utils/exeflat.c, utils/makefile, utils/upxdevic.asm, utils/upxentry.asm
Copying the commit message of the first commit in this PR:
This format has several advantages:
* The CONFIG block need not be moved.
* The entire compressed image (depacker and payload) need not be moved another time before the UPX depacker's own operation.
* The CONFIG block always lives at 00602h, and the kernel need not be aware whether it was compressed for detecting which CONFIG block to use.
* Support for compressed images beyond 64 KiB for free. (The assembly define TEST_FILL_INIT_TEXT can be passed in NASMENV to test this support with 32 KiB of LFSR output.)
* A subsequent commit will shorten the stub to 64 bytes, compared to the prior 32 + 45 = 77 bytes, with no loss of features. (The packed payload is a bit shorter too.) (PR: This commit is included in the PR.)
* The new stub …
=> ecm new exeflat format

kernel/fcbfns.c
On both MS-DOS 2.11 and MS-DOS 5.0, the "parse filename to FCB" syscall (`int 0x21`, function `0x29`), when it encounters an invalid drive letter, will still continue parsing the file name, and return with `al` = `0xff` _and_ `ds:si` pointing after the parsed file name.
E.g. given an input like `z:foo.bar,baz` &mdash; assuming `z` is not a valid drive letter &mdash; the syscall will return `al` = `0xff` and `ds:si` pointing at the comma.
This patch modifies the FreeDOS kernel to follow the same behaviour.
Thank you!
=> FCB (int 21h func 29h): should keep parsing name even if drive letter invalid

kernel/fcbfns.c
This is a follow-up to my earlier pull request at https://github.com/FDOS/kernel/pull/82 .
In the earlier patch, I modified the "parse filename to FCB" syscall (`int 0x21`, function `0x29`) so that, even if it encounters an invalid drive letter, it will still continue parsing the file name after the drive letter.
However, I forgot to add a needed check: the "drive letter" can be invalid, but must not be a file name delimiter (e.g. a control character).  E.g. given an input like `\r:foo.bar,baz` &mdash; where `\r` is the carriage return character &mdash; the syscall should stop immediately at the `\r`, and not try to parse beyond it.
This new pull request adds this check.
Thank you!
=> FCB (int 21h func 29h): should not accept field separator as "drive letter"

sys/sys.c
Fix two bugs in SYS: The int86 for gcc should preserve ds, and not defining WITHFAT32 should still allow to build SYS.
The former caused seemingly random crashes and impacted even a debugger trying to examine the program, as it lead to the code corrupting data in the DOS data segment.
The latter was a minor issue leading to build failure.
=> ecm sys fix

boot/boot.asm, boot/boot32.asm, boot/boot32lb.asm, boot/oemboot.asm, kernel/fatfs.c, sys/sys.c
This should be compatible to Enhanced DR-DOS.
Tested by building a boot image like the following:
nasm ../ldosmbr/oldmbr.asm -o oldmbr.bin
nasm ../ldosboot/boot.asm -D_FAT16=1 -I ../lmacros/ \
-D_LOAD_NAME="'LDEBUG'" -o boot16.bin
nasm bootimg.asm -I ../lmacros/ -o disk16.img \
-D_MBR -D_ALIGNDATA -D_BOOTPATCHFILE=boot16.bin \
-D_MBRPATCHFILE=oldmbr.bin -D_BPE=16 \
-D_SPI='(_SPC * 5000)' -D_NUMROOT=512 -D_SPC=256 \
-D_SPF='((_SPI / _SPC + 255) / 256)' \
-D_PAYLOADFILE=../ldebug/bin/ldebug.com,quit.com,\
::rename,../k256spc/bin/kernel.sys,kernel.sys,\
command.com,::fill,1,32,autoexec.bat
The repos bootimg, ldosboot, ldosmbr, and lmacros are available at https://hg.pushbx.org/ecm/
The file ldebug.com is a recent bootable lDebug debugger. The file command.com is a recent FreeCOM. The file …
=> fatfs.c: allow bpbSectorsPerCluster == 0 to mean 256

sys/sys.c
Fixes https://github.com/FDOS/kernel/issues/93 and also completes https://github.com/FDOS/kernel/pull/95 (SYS was overlooked because of using a different field name for the SPC entry of the BPB.)
=> ecm sys fs fix

ci_build.sh, hdr/network.h, kernel/dosfns.c, kernel/int2f.asm, kernel/proto.h
To be able to return free space on larger non local disks, the redirector needs an extension. Dosemu2 has implemented this function and FDPP has an almost identical patch to this. If the extension is not implemented by your chosen redirector, then fallback to the standard 110c function is done for int21/7303.
With this patch up to 2TB (with Dosemu2 reporting in 512 blocks) can be displayed.
=> DosGetExtFree: Use new redirector function 11a3

kernel/inthndlr.c
Based on a patch https://github.com/dosemu2/fdpp/commit/e7fe81d458 for FDDP by @stsp
[fixes #101]
=> inthndlr: align hma size to para

kernel/asmsupt.asm, kernel/config.c, kernel/init-mod.h, kernel/kernel.asm, kernel/kernel.ld, kernel/main.c, mkfiles/gcc.mak
Allows lDebug loaded as a device driver to access the environment variables set so far.
=> ecm fdconfig env

kernel/newstuff.c
Picked from the commit at https://github.com/dosemu2/fdpp/commit/fe1c4dc7fe5a2218d3badf90c3a8e43550da5821
The referenced issue is at https://github.com/dosemu2/fdpp/issues/212
The patch was applied using unix2dos on the patch file then `patch -p1 --binary` with the patch file as stdin. The original used a new define for the maximum path length. As there is no difference to our current SFTMAX define I changed this hunk to retain the SFTMAX use.
This fixes a bug when eg function 3Dh receives a buffer that starts with ".\\" but the byte in memory before this buffer happens to be also a dot. I ran into this problem semi-randomly during building EDR-DOS with the most recent WarpLink build. If WarpLink was placed somewhat low in the Low Memory Area then one of its function 3Dh calls would …
=> truename: fix array overrun (pick from fdpp)

kernel/asmsupt.asm, kernel/config.c, kernel/kernel.ld
This allows to delete environment variables using an empty `set var=`, and will also delete an existing variable if the name of a variable to set matches an existing variable. (If after the deletion there would still not be enough space for the new variable, the error is displayed and the existing variable is unchanged.)
https://github.com/FDOS/kernel/pull/107 is not required but would still be good.
=> ecm fdconfig var del

utils/exeflat.c
During build the kernel silently was not updated, because a temporary file could not be overwritten by exeflat (it was created by exeflat in a previous run).
The new behaviour is, that exeflat terminates with error, if the file renaming can not be performed. The temporary binary is also deleted after compressing the kernel.
=> fix exeflat not deleting temporary file

kernel/initdisk.c
Hey Jeremy,
I had a look at the recent changes and found some places where I am not sure that it is correct. For instance, I think `ExtLBAForce` originally was meant to force LBA access for partitions contained inside an extended partition of type LBA (0x0E).
ExtLBAForce is now set in `LBA_Get_Drive_Parameters` to `InitKernelConfig.ForceLBA`. I understand you somewhat wanted to force the use of LBA (it is not clear to me in what case exactly), but setting `ExtLBAForce` in `LBA_Get_Drive_Parameters` is in my opinion a) the wrong variable and b) the wrong place for it.
I relocated the `ExtLBAForce` setting to `ProcessDisk`, setting it initially to zero. I think this is the right layer of abstraction for it. `LBA_Get_Drive_Parameters` should only do what it is named after: getting drive …
=> initdisk: actually restrict disk size to 2TB instead of modulo 2TB, fix ExtLBAForce usage

boot/boot32.asm, boot/boot32lb.asm
This fixes the incompatibility noted in #119 and also another bug of the 8086 CHS FAT32 loader. The latter prevented successful loading if the kernel file's clusters did not fit within the first FAT sector.
Also, the 8086 CHS FAT32 loader will now emit an exclamation mark and a beep when an error occurs, rather than staying silent.
=> ecm boot32 dl

hdr/win.h, kernel/inthndlr.c, kernel/kernel.asm
I copied `config.m` to `config.mak` and enabled the `-DWIN31SUPPORT` switch like so:
```
kwin31$ tail config.mak
XFAT=32
ALLCFLAGS=-DWIN31SUPPORT
NASMFLAGS=-DWIN31SUPPORT
```
(Is this correct? Is there a better way to set this flag?)
Prior to this commit building with `-DWIN31SUPPORT` would fail with errors from NASM:
```
nasm -Dgcc -DWIN31SUPPORT -DWITHFAT32 -i../hdr/ -DXCPU=386 -felf -o kernel.obj kernel.asm
kernel.asm:610: error: ELF format does not support segment base references
kernel.asm:613: error: ELF format does not support segment base references
kernel.asm:614: error: ELF format does not support this use of WRT
```
I did a small validity check on the resulting structure and it seems to be correct when I call [int 2Fh function …
=> allow gcc build to succeed with -DWIN31SUPPORT

kernel/main.c
Fix initialisation of the environment. It is already written in PSPInit. Same function also wanted to initialise the command line tail, but we don't want that to properly init as environment.
=> ecm fdconfig env 2

kernel/intr.asm
Here's example output of what happens when setting the CheckDebugger configuration item, then loading the kernel in bootable lDebug and running it:
```
-g
FreeDOS kernel - GIT (build 2043 OEM:0xfd) [compiled Jun  4 2022]
Kernel compatibility 7.10 - GNUC - FAT32 support
(C) Copyright 1995-2022 Pasquale J. Villani and The FreeDOS Project.
All Rights Reserved. This is free software and comes with ABSOLUTELY NO
WARRANTY; you can redistribute it and/or modify it under the terms of the
GNU General Public License as published by the Free Software Foundation;
either version 2, or (at your option) any later version.
Unexpected single-step interrupt
AX=3173 BX=0030 CX=FF01 DX=C781 SP=24D0 BP=24FA SI=0C7C DI=5058
DS=80E5 ES=013D SS=80E5 CS=7C80 IP=0204 NV DN DI PL NZ NA PO NC
7C80:0204 1F …
```
=> intr: avoid random trace in (init_)call_intr

kernel/kernel.asm, kernel/main.c
fix error that probably never would happen where if nunits is 0 would overwrite nonexistent dpb next pointer with -1
=> rework update_dcb() to avoid potential access uninitialized memory

kernel/config.c
allows correctly parsing lines like SHELL=4DOS.COM which otherwise strips 4 leading to looking for shell of "DOS.COM"
=> fix bug#121 don't look for 123? unless still looking for verb at start of line

kernel/makefile
Double ampersands are not supported by DOS command line interpreters. The previous would work only on Windows (2000 and higher, I think).
=> Make build work on DOS

boot/boot.asm, boot/boot32.asm, boot/boot32lb.asm, boot/magic.mac, boot/makefile, boot/oemboot.asm, sys/sys.c
Several boot loader improvements:
- Bug #127 fixed, files up to 128 KiB rounded up size work now
- Load segment 0x60 to 0x200 fully supported
- Memory map comments fixed and updated
- SYS checks that it seems to patch the correct magic offsets
- Mark all magic offsets in SYS and the loader sources
- On magic offset mismatch the new offset is displayed by the NASM error message
- Create listing files with correct names, fixes bug #97
=> ecm boot overlap

.github/workflows/ci-build.yml, build.bat, ci_build.sh, ci_prereq.sh, ci_test.sh, kernel/makefile, makefile
I added an OpenWatcom(DOS) build to the CI, and also an optional Turbo C 2.01 compile and test. There are a couple of problems with using Turbo C:
- I don't know where / how to host the Turbo C compiler as I don't want to make it publicly available. I can't use the official source as I believe it requires sign up to download.
- Building the current kernel with Turbo C is broken and has been for a few years. I don't want to add a broken build into CI as it will obscure any new breakage.
So for now the CI checks to see if Turbo C is installed at `C:\TC201` and will try to build and test with it if found, otherwise it will be silently skipped.
=> CI add Watcom and optionally Turbo C 2.01 builds

kernel/dsk.c, kernel/inthndlr.c
getbpb now returns 0 instead of S_DONE in case of an uninitialized partition, copying the default BPB into the BPB.
The previous return of S_DONE in case of uninitialized partitions resulted in rp->r_bpptr not getting set in bldbpb. This in combination with indicating success resulted in garbage returned via rp->r_bpptr.
The DPB values are now being set to the default BPB ones in media_check https://github.com/FDOS/kernel/blob/ea951d8136444e334f06a313465b5844f738354e/kernel/fatfs.c#L1728 via call to bpb_to_dpb in case of an uninitialized partition. This may have side effects. But because DF_NOACCESS is still set, I think it is the right way to do it.
The commit also masks high bit of AL for INT25/26 containing the drive number. Some programs may set the bit according to RBIL:
"examination …
=> fix issue #144 by correcting getbpb return code

ci_build.sh
The latest build got some compatibilty fixes so we can now start using it again [fixes #138]
=> CI: Switch back to openwatcom current build

kernel/config.c, kernel/main.c
Fixes #148 by using DynAlloc in update_dcb() if memory system is not initialized yet.
=> fixes #148

sys/sys.c
Running on DR-DOS v7.03, the int 25h call zeroes di leading to a crash here when di is expected to preserve the stack pointer. So push di twice and pop it twice. The second pop always gets the saved sp, regardless of whether int 21h or int 25h/26h are used.
Refer to https://github.com/SvarDOS/edrdos/issues/57#issuecomment-2119360035
=> sys: fix, work on DOS versions that clobber di in int 25h/26h

.gitignore, ci_build.sh
- ignore _downloads, _output and _watcom sub-directories contents in git
- use _downloads sub-directory for CI buil OW snapshot download
=> CI-build: a little simplify CI-build development

kernel/config.c, kernel/inthndlr.c, kernel/makefile, kernel/newstuff.c
TC 2.0 uses internal function SCOPY@ for copying structures (not implemented), it is replaced by fmemcpy
TC 2.0 make cannot handle $@ macro, replaced by exact name
correct type mismatches
=> tc2-build: correct various build breaks for Turbo C 2.0 build

ci_build.sh, kernel/makefile, utils/exeflat.c
the command line can overflow DOS max length that it fixes this issue
switch on UPX for DOS CI build
=> exeflat: add support for response file to exeflat utility

mkfiles/owlinux.mak, mkfiles/owwin.mak, mkfiles/watcom.mak
move only options which is related to the host environment not for target
-zq quiet output (all)
-fo=.obj set default extension for object file to .obj instead .o (Linux only)
=> ow-build: add global compiler control option to CC and CL macros

mkfiles/watcom.mak
now FreeDOS own implementation is used
this module is removed from the library to prevent misuse of this module
=> libm.lib: The i4m module from OW-CRTL is no longer used

hdr/win.h, kernel/init-mod.h, kernel/inthndlr.c
these symbols are in LGROUP and generaly cannot be addressed by DGROUP:offset
for Turbo C DGROUP offset overflow because symbols are too far to be addressed by DGROUP offset
=> far-fix: symbols BIOSInt13, UserInt13 and BIOSInt19 are far (in LGROUP)

kernel/main.c
This caused the kernel to hang when loading NETDRIVE.SYS
=> fix list traversal bug in update_dcb()

kernel/config.c, kernel/initdisk.c, kernel/main.c
This PR eliminates lone Carriage Returns used by the kernel, if SWITCHES=/F or SWITCHES=/N is used in fdconfig.sys. Reason: They annoy me in dosemu2 output when redirected into a file.
=> ecm boot no cr

kernel/blockio.c, kernel/inthndlr.c
* Reject allocation call with too large requested size, rather than allocating the remaining HMA.
* Align returned offset to paragraph boundary.
* Allow to allocate up to the very last byte of the HMA, rather than 1 byte less.
* Pass last allocated byte to AllocateHMASpace instead of the byte past it, which would carry for a full allocation.
=> fix 2F.4A MS-DOS v5 style HMA access services

ci_prereq.sh
Sometimes DOS packages can have upper or mixed case filenames that Linux unzip doesn't recognise as needing downcasing.
=> CI: Force lower case when unzipping

.github/workflows/ci-build.yml
Now that the ia16-gcc compiler is available on Ubuntu Noble we can update the runner.
=> CI: Update to use Ubuntu 24.04 runner
